/**
 * highlight.js 语法模块的按需加载器：键 = text/markdown `codeLanguage` 的规范 id = 模块名。
 *
 * 每种语法都是独立的动态 import，Vite 拆成各自的小分包（多数 1–7 KB gzip）：核心只装一次，
 * 语法在页面第一次遇到该语言的代码块时才下载。这里只列本产品会认的语法；不在这里的 id
 * 只做等宽排版。plaintext 刻意不列——纯文本没有 token，注册它只是白跑一趟。
 *
 * 本文件除类型外不导入任何东西，方便测试用 data URL 转译后与 markdown 的语言表核对。
 */

import type { LanguageFn } from "highlight.js";

export type LanguageModule = { default: LanguageFn };

export const LANGUAGE_LOADERS: Record<string, () => Promise<LanguageModule>> = {
  // 科学计算 / 统计
  python: () => import("highlight.js/lib/languages/python"),
  r: () => import("highlight.js/lib/languages/r"),
  julia: () => import("highlight.js/lib/languages/julia"),
  matlab: () => import("highlight.js/lib/languages/matlab"),
  scilab: () => import("highlight.js/lib/languages/scilab"),
  mathematica: () => import("highlight.js/lib/languages/mathematica"),
  maxima: () => import("highlight.js/lib/languages/maxima"),
  stan: () => import("highlight.js/lib/languages/stan"),
  sas: () => import("highlight.js/lib/languages/sas"),
  stata: () => import("highlight.js/lib/languages/stata"),
  gams: () => import("highlight.js/lib/languages/gams"),
  gauss: () => import("highlight.js/lib/languages/gauss"),
  fortran: () => import("highlight.js/lib/languages/fortran"),
  excel: () => import("highlight.js/lib/languages/excel"),
  // 通用编程
  c: () => import("highlight.js/lib/languages/c"),
  cpp: () => import("highlight.js/lib/languages/cpp"),
  csharp: () => import("highlight.js/lib/languages/csharp"),
  java: () => import("highlight.js/lib/languages/java"),
  kotlin: () => import("highlight.js/lib/languages/kotlin"),
  scala: () => import("highlight.js/lib/languages/scala"),
  go: () => import("highlight.js/lib/languages/go"),
  rust: () => import("highlight.js/lib/languages/rust"),
  swift: () => import("highlight.js/lib/languages/swift"),
  objectivec: () => import("highlight.js/lib/languages/objectivec"),
  javascript: () => import("highlight.js/lib/languages/javascript"),
  typescript: () => import("highlight.js/lib/languages/typescript"),
  coffeescript: () => import("highlight.js/lib/languages/coffeescript"),
  livescript: () => import("highlight.js/lib/languages/livescript"),
  dart: () => import("highlight.js/lib/languages/dart"),
  php: () => import("highlight.js/lib/languages/php"),
  ruby: () => import("highlight.js/lib/languages/ruby"),
  perl: () => import("highlight.js/lib/languages/perl"),
  lua: () => import("highlight.js/lib/languages/lua"),
  groovy: () => import("highlight.js/lib/languages/groovy"),
  gradle: () => import("highlight.js/lib/languages/gradle"),
  haskell: () => import("highlight.js/lib/languages/haskell"),
  erlang: () => import("highlight.js/lib/languages/erlang"),
  elixir: () => import("highlight.js/lib/languages/elixir"),
  clojure: () => import("highlight.js/lib/languages/clojure"),
  lisp: () => import("highlight.js/lib/languages/lisp"),
  scheme: () => import("highlight.js/lib/languages/scheme"),
  ocaml: () => import("highlight.js/lib/languages/ocaml"),
  reasonml: () => import("highlight.js/lib/languages/reasonml"),
  fsharp: () => import("highlight.js/lib/languages/fsharp"),
  sml: () => import("highlight.js/lib/languages/sml"),
  elm: () => import("highlight.js/lib/languages/elm"),
  haxe: () => import("highlight.js/lib/languages/haxe"),
  nim: () => import("highlight.js/lib/languages/nim"),
  crystal: () => import("highlight.js/lib/languages/crystal"),
  d: () => import("highlight.js/lib/languages/d"),
  delphi: () => import("highlight.js/lib/languages/delphi"),
  ada: () => import("highlight.js/lib/languages/ada"),
  vbnet: () => import("highlight.js/lib/languages/vbnet"),
  vbscript: () => import("highlight.js/lib/languages/vbscript"),
  basic: () => import("highlight.js/lib/languages/basic"),
  prolog: () => import("highlight.js/lib/languages/prolog"),
  coq: () => import("highlight.js/lib/languages/coq"),
  smalltalk: () => import("highlight.js/lib/languages/smalltalk"),
  tcl: () => import("highlight.js/lib/languages/tcl"),
  awk: () => import("highlight.js/lib/languages/awk"),
  applescript: () => import("highlight.js/lib/languages/applescript"),
  actionscript: () => import("highlight.js/lib/languages/actionscript"),
  autohotkey: () => import("highlight.js/lib/languages/autohotkey"),
  vala: () => import("highlight.js/lib/languages/vala"),
  qml: () => import("highlight.js/lib/languages/qml"),
  processing: () => import("highlight.js/lib/languages/processing"),
  arduino: () => import("highlight.js/lib/languages/arduino"),
  glsl: () => import("highlight.js/lib/languages/glsl"),
  openscad: () => import("highlight.js/lib/languages/openscad"),
  q: () => import("highlight.js/lib/languages/q"),
  brainfuck: () => import("highlight.js/lib/languages/brainfuck"),
  // 硬件 / 底层
  verilog: () => import("highlight.js/lib/languages/verilog"),
  vhdl: () => import("highlight.js/lib/languages/vhdl"),
  llvm: () => import("highlight.js/lib/languages/llvm"),
  wasm: () => import("highlight.js/lib/languages/wasm"),
  x86asm: () => import("highlight.js/lib/languages/x86asm"),
  armasm: () => import("highlight.js/lib/languages/armasm"),
  mipsasm: () => import("highlight.js/lib/languages/mipsasm"),
  avrasm: () => import("highlight.js/lib/languages/avrasm"),
  gcode: () => import("highlight.js/lib/languages/gcode"),
  // Shell / 系统 / 构建
  bash: () => import("highlight.js/lib/languages/bash"),
  shell: () => import("highlight.js/lib/languages/shell"),
  powershell: () => import("highlight.js/lib/languages/powershell"),
  dos: () => import("highlight.js/lib/languages/dos"),
  makefile: () => import("highlight.js/lib/languages/makefile"),
  cmake: () => import("highlight.js/lib/languages/cmake"),
  dockerfile: () => import("highlight.js/lib/languages/dockerfile"),
  nginx: () => import("highlight.js/lib/languages/nginx"),
  apache: () => import("highlight.js/lib/languages/apache"),
  nix: () => import("highlight.js/lib/languages/nix"),
  puppet: () => import("highlight.js/lib/languages/puppet"),
  vim: () => import("highlight.js/lib/languages/vim"),
  nsis: () => import("highlight.js/lib/languages/nsis"),
  // 数据 / 配置 / 标记
  json: () => import("highlight.js/lib/languages/json"),
  yaml: () => import("highlight.js/lib/languages/yaml"),
  ini: () => import("highlight.js/lib/languages/ini"),
  properties: () => import("highlight.js/lib/languages/properties"),
  xml: () => import("highlight.js/lib/languages/xml"),
  css: () => import("highlight.js/lib/languages/css"),
  scss: () => import("highlight.js/lib/languages/scss"),
  less: () => import("highlight.js/lib/languages/less"),
  stylus: () => import("highlight.js/lib/languages/stylus"),
  sql: () => import("highlight.js/lib/languages/sql"),
  pgsql: () => import("highlight.js/lib/languages/pgsql"),
  graphql: () => import("highlight.js/lib/languages/graphql"),
  protobuf: () => import("highlight.js/lib/languages/protobuf"),
  thrift: () => import("highlight.js/lib/languages/thrift"),
  http: () => import("highlight.js/lib/languages/http"),
  diff: () => import("highlight.js/lib/languages/diff"),
  markdown: () => import("highlight.js/lib/languages/markdown"),
  latex: () => import("highlight.js/lib/languages/latex"),
  asciidoc: () => import("highlight.js/lib/languages/asciidoc"),
  django: () => import("highlight.js/lib/languages/django"),
  handlebars: () => import("highlight.js/lib/languages/handlebars"),
  twig: () => import("highlight.js/lib/languages/twig"),
  erb: () => import("highlight.js/lib/languages/erb"),
  gherkin: () => import("highlight.js/lib/languages/gherkin"),
  dns: () => import("highlight.js/lib/languages/dns"),
  abnf: () => import("highlight.js/lib/languages/abnf"),
  bnf: () => import("highlight.js/lib/languages/bnf"),
  ebnf: () => import("highlight.js/lib/languages/ebnf"),
};

/**
 * 内嵌子语言：这些语法在高亮时按名字查找别的语法（HTML 里的 <script>/<style>、模板里的宿主
 * 语言、JSX 里的标签）。找不到时 highlight.js 会把那一段按纯文本放过、不报错，所以这只是
 * 让嵌入部分也有颜色的增强——加载器与主语法一并装好即可。只列一层，不做传递（xml ↔
 * javascript 互相引用，递归等待会死锁）。
 */
export const LANGUAGE_DEPENDENCIES: Record<string, string[]> = {
  xml: ["css", "javascript"],
  javascript: ["xml", "css"],
  typescript: ["xml", "css"],
  markdown: ["xml"],
  django: ["xml"],
  handlebars: ["xml"],
  twig: ["xml"],
  erb: ["xml", "ruby"],
};
