"""数学建模 Agent 领域内核。

只定义领域语义与端口，不依赖 FastAPI、Tauri、具体 UI、沙盒实现或 Workflow 供应商
SDK。工具、技能与执行环境通过端口注入，因此本包位于依赖图最底层。
"""

from .engine import AdvanceOutcome, TaskRunEngine
from .errors import CATALOG, AgentError, Disposition, ErrorCode, ErrorInfo
from .graph import (
    DEFAULT_GRAPH_MODE,
    GRAPH_MODE_ENV,
    GRAPH_MODES,
    LINEAR_V1_GATES,
    GateDecl,
    GraphEdge,
    GraphNode,
    GraphScheduler,
    GraphSpec,
    LinearScheduler,
    Scheduler,
    SchedulingDivergence,
    ShadowComparator,
    linear_v1,
    resolve_graph_mode,
    schedulers_for_mode,
    stage_output_schema_id,
)
from .models import (
    AgentEvent,
    ArtifactRef,
    EventType,
    Failure,
    ReviewRequest,
    StepRun,
    StepStatus,
    TaskRunSnapshot,
    ToolResult,
)
from .nodes import NodeContext, NodeRegistry, NodeResult, StepNode
from .ports import (
    ArtifactStore,
    Clock,
    EventSink,
    FixedClock,
    IdGenerator,
    InMemoryArtifactStore,
    InMemoryEventSink,
    KnowledgePort,
    LlmPort,
    NodeServices,
    SequentialIdGenerator,
    SystemClock,
    ToolInvoker,
    UuidIdGenerator,
)
from .reducer import ReduceError, SequenceError, apply_event, replay_events
from .states import (
    TERMINAL_STATES,
    WORK_SEQUENCE,
    WORK_STATES,
    TaskState,
    TransitionError,
    assert_transition,
    can_transition,
    next_work_state,
)

__all__ = [
    "AdvanceOutcome",
    "AgentError",
    "AgentEvent",
    "ArtifactRef",
    "ArtifactStore",
    "CATALOG",
    "Clock",
    "DEFAULT_GRAPH_MODE",
    "Disposition",
    "ErrorCode",
    "ErrorInfo",
    "EventSink",
    "EventType",
    "Failure",
    "FixedClock",
    "GRAPH_MODES",
    "GRAPH_MODE_ENV",
    "GateDecl",
    "GraphEdge",
    "GraphNode",
    "GraphScheduler",
    "GraphSpec",
    "IdGenerator",
    "InMemoryArtifactStore",
    "InMemoryEventSink",
    "KnowledgePort",
    "LINEAR_V1_GATES",
    "LinearScheduler",
    "LlmPort",
    "NodeContext",
    "NodeRegistry",
    "NodeResult",
    "NodeServices",
    "ReduceError",
    "ReviewRequest",
    "Scheduler",
    "SchedulingDivergence",
    "SequenceError",
    "SequentialIdGenerator",
    "ShadowComparator",
    "StepNode",
    "StepRun",
    "StepStatus",
    "SystemClock",
    "TERMINAL_STATES",
    "TaskRunEngine",
    "TaskRunSnapshot",
    "TaskState",
    "ToolInvoker",
    "ToolResult",
    "TransitionError",
    "UuidIdGenerator",
    "WORK_SEQUENCE",
    "WORK_STATES",
    "apply_event",
    "assert_transition",
    "can_transition",
    "linear_v1",
    "next_work_state",
    "replay_events",
    "resolve_graph_mode",
    "schedulers_for_mode",
    "stage_output_schema_id",
]
